# Generated by Django 5.0.6 on 2024-05-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommand", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload_image",
            name="컬럼_업로드날짜",
        ),
        migrations.AddField(
            model_name="upload_image",
            name="title",
            field=models.CharField(blank=True, max_length=100, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="upload_image",
            name="upload_image",
            field=models.ImageField(
                blank=True, upload_to="media/images/", verbose_name="이미지"
            ),
        ),
    ]
